// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Flow {
    #[prost(message, optional, tag = "1")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    /// uuid is a universally unique identifier for this flow.
    #[prost(string, tag = "34")]
    pub uuid: ::prost::alloc::string::String,
    /// emitter identifies the source that emitted the flow.
    #[prost(message, optional, tag = "41")]
    pub emitter: ::core::option::Option<Emitter>,
    #[prost(enumeration = "Verdict", tag = "2")]
    pub verdict: i32,
    /// only applicable to Verdict = DROPPED.
    /// deprecated in favor of drop_reason_desc.
    #[deprecated]
    #[prost(uint32, tag = "3")]
    pub drop_reason: u32,
    /// auth_type is the authentication type specified for the flow in Cilium Network Policy.
    /// Only set on policy verdict events.
    #[prost(enumeration = "AuthType", tag = "35")]
    pub auth_type: i32,
    /// l2
    #[prost(message, optional, tag = "4")]
    pub ethernet: ::core::option::Option<Ethernet>,
    /// l3
    #[prost(message, optional, tag = "5")]
    pub ip: ::core::option::Option<Ip>,
    /// l4
    #[prost(message, optional, tag = "6")]
    pub l4: ::core::option::Option<Layer4>,
    #[prost(message, optional, tag = "39")]
    pub tunnel: ::core::option::Option<Tunnel>,
    #[prost(message, optional, tag = "8")]
    pub source: ::core::option::Option<Endpoint>,
    #[prost(message, optional, tag = "9")]
    pub destination: ::core::option::Option<Endpoint>,
    #[prost(enumeration = "FlowType", tag = "10")]
    pub r#type: i32,
    /// NodeName is the name of the node from which this Flow was captured.
    #[prost(string, tag = "11")]
    pub node_name: ::prost::alloc::string::String,
    /// node labels in `foo=bar` format.
    #[prost(string, repeated, tag = "37")]
    pub node_labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// all names the source IP can have.
    #[prost(string, repeated, tag = "13")]
    pub source_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// all names the destination IP can have.
    #[prost(string, repeated, tag = "14")]
    pub destination_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// L7 information. This field is set if and only if FlowType is L7.
    #[prost(message, optional, tag = "15")]
    pub l7: ::core::option::Option<Layer7>,
    /// Deprecated. This suffers from false negatives due to protobuf not being
    /// able to distinguish between the value being false or it being absent.
    /// Please use is_reply instead.
    #[deprecated]
    #[prost(bool, tag = "16")]
    pub reply: bool,
    /// EventType of the originating Cilium event
    #[prost(message, optional, tag = "19")]
    pub event_type: ::core::option::Option<CiliumEventType>,
    /// source_service contains the service name of the source
    #[prost(message, optional, tag = "20")]
    pub source_service: ::core::option::Option<Service>,
    /// destination_service contains the service name of the destination
    #[prost(message, optional, tag = "21")]
    pub destination_service: ::core::option::Option<Service>,
    /// traffic_direction of the connection, e.g. ingress or egress
    #[prost(enumeration = "TrafficDirection", tag = "22")]
    pub traffic_direction: i32,
    /// policy_match_type is only applicable to the cilium event type PolicyVerdict
    /// <https://github.com/cilium/cilium/blob/e831859b5cc336c6d964a6d35bbd34d1840e21b9/pkg/monitor/datapath_policy.go#L50>
    #[prost(uint32, tag = "23")]
    pub policy_match_type: u32,
    /// Only applicable to cilium trace notifications, blank for other types.
    #[prost(enumeration = "TraceObservationPoint", tag = "24")]
    pub trace_observation_point: i32,
    /// Cilium datapath trace reason info.
    #[prost(enumeration = "TraceReason", tag = "36")]
    pub trace_reason: i32,
    /// Cilium datapath filename and line number. Currently only applicable when
    /// Verdict = DROPPED.
    #[prost(message, optional, tag = "38")]
    pub file: ::core::option::Option<FileInfo>,
    /// IPTraceID relates to the trace ID in the IP options of a packet.
    #[prost(message, optional, tag = "40")]
    pub ip_trace_id: ::core::option::Option<IpTraceId>,
    /// only applicable to Verdict = DROPPED.
    #[prost(enumeration = "DropReason", tag = "25")]
    pub drop_reason_desc: i32,
    /// is_reply indicates that this was a packet (L4) or message (L7) in the
    /// reply direction. May be absent (in which case it is unknown whether it
    /// is a reply or not).
    #[prost(message, optional, tag = "26")]
    pub is_reply: ::core::option::Option<bool>,
    /// Only applicable to cilium debug capture events, blank for other types
    #[prost(enumeration = "DebugCapturePoint", tag = "27")]
    pub debug_capture_point: i32,
    /// interface is the network interface on which this flow was observed
    #[prost(message, optional, tag = "28")]
    pub interface: ::core::option::Option<NetworkInterface>,
    /// proxy_port indicates the port of the proxy to which the flow was forwarded
    #[prost(uint32, tag = "29")]
    pub proxy_port: u32,
    /// trace_context contains information about a trace related to the flow, if
    /// any.
    #[prost(message, optional, tag = "30")]
    pub trace_context: ::core::option::Option<TraceContext>,
    /// sock_xlate_point is the socket translation point.
    /// Only applicable to TraceSock notifications, blank for other types
    #[prost(enumeration = "SocketTranslationPoint", tag = "31")]
    pub sock_xlate_point: i32,
    /// socket_cookie is the Linux kernel socket cookie for this flow.
    /// Only applicable to TraceSock notifications, zero for other types
    #[prost(uint64, tag = "32")]
    pub socket_cookie: u64,
    /// cgroup_id of the process which emitted this event.
    /// Only applicable to TraceSock notifications, zero for other types
    #[prost(uint64, tag = "33")]
    pub cgroup_id: u64,
    /// This is a temporary workaround to support summary field for pb.Flow without
    /// duplicating logic from the old parser. This field will be removed once we
    /// fully migrate to the new parser.
    #[deprecated]
    #[prost(string, tag = "100000")]
    pub summary: ::prost::alloc::string::String,
    /// extensions can be used to add arbitrary additional metadata to flows.
    /// This can be used to extend functionality for other Hubble compatible
    /// APIs, or experiment with new functionality without needing to change the public API.
    #[prost(message, optional, tag = "150000")]
    pub extensions: ::core::option::Option<::prost_types::Any>,
    /// The CiliumNetworkPolicies allowing the egress of the flow.
    #[prost(message, repeated, tag = "21001")]
    pub egress_allowed_by: ::prost::alloc::vec::Vec<Policy>,
    /// The CiliumNetworkPolicies allowing the ingress of the flow.
    #[prost(message, repeated, tag = "21002")]
    pub ingress_allowed_by: ::prost::alloc::vec::Vec<Policy>,
    /// The CiliumNetworkPolicies denying the egress of the flow.
    #[prost(message, repeated, tag = "21004")]
    pub egress_denied_by: ::prost::alloc::vec::Vec<Policy>,
    /// The CiliumNetworkPolicies denying the ingress of the flow.
    #[prost(message, repeated, tag = "21005")]
    pub ingress_denied_by: ::prost::alloc::vec::Vec<Policy>,
    /// The set of Log values for policies that matched this flow.
    /// If no matched policies have an explicit log value configured,
    /// this list is empty. Duplicate values are elided; each
    /// entry is unique.
    #[prost(string, repeated, tag = "21006")]
    pub policy_log: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Aggregate contains flow aggregation counters when flow aggregation is enabled.
    /// This field is only populated for aggregated flows.
    #[prost(message, optional, tag = "21007")]
    pub aggregate: ::core::option::Option<Aggregate>,
}
/// Emitter identifies the source that emits a Hubble flow.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Emitter {
    /// name identifies the emitter.
    /// The name should be capitalized ("Hubble", not "hubble" nor "HUBBLE").
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// version identifiers the emitter version.
    /// The version should not contain a 'v' prefix as sometimes seen ("1.19.0",
    /// not "v1.19.0").
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub line: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Layer4 {
    #[prost(oneof = "layer4::Protocol", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub protocol: ::core::option::Option<layer4::Protocol>,
}
/// Nested message and enum types in `Layer4`.
pub mod layer4 {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Protocol {
        #[prost(message, tag = "1")]
        Tcp(super::Tcp),
        #[prost(message, tag = "2")]
        Udp(super::Udp),
        /// ICMP is technically not L4, but mutually exclusive with the above
        #[prost(message, tag = "3")]
        IcmPv4(super::IcmPv4),
        #[prost(message, tag = "4")]
        IcmPv6(super::IcmPv6),
        #[prost(message, tag = "5")]
        Sctp(super::Sctp),
        #[prost(message, tag = "6")]
        Vrrp(super::Vrrp),
        #[prost(message, tag = "7")]
        Igmp(super::Igmp),
    }
}
/// Message for L7 flow, which roughly corresponds to Cilium's accesslog [LogRecord](<https://github.com/cilium/cilium/blob/728c79e427438ab6f8d9375b62fccd6fed4ace3a/pkg/proxy/accesslog/record.go#L141>):
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Layer7 {
    #[prost(enumeration = "L7FlowType", tag = "1")]
    pub r#type: i32,
    /// Latency of the response
    #[prost(uint64, tag = "2")]
    pub latency_ns: u64,
    /// L7 field. This field is set if and only if FlowType is L7.
    #[prost(oneof = "layer7::Record", tags = "100, 101, 102")]
    pub record: ::core::option::Option<layer7::Record>,
}
/// Nested message and enum types in `Layer7`.
pub mod layer7 {
    /// L7 field. This field is set if and only if FlowType is L7.
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Record {
        #[prost(message, tag = "100")]
        Dns(super::Dns),
        #[prost(message, tag = "101")]
        Http(super::Http),
        #[prost(message, tag = "102")]
        Kafka(super::Kafka),
    }
}
/// TraceContext contains trace context propagation data, i.e. information about a
/// distributed trace.
/// For more information about trace context, check the [W3C Trace Context specification](<https://www.w3.org/TR/trace-context/>).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraceContext {
    /// parent identifies the incoming request in a tracing system.
    #[prost(message, optional, tag = "1")]
    pub parent: ::core::option::Option<TraceParent>,
}
/// TraceParent identifies the incoming request in a tracing system.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraceParent {
    /// trace_id is a unique value that identifies a trace. It is a byte array
    /// represented as a hex string.
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Endpoint {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(uint32, tag = "2")]
    pub identity: u32,
    #[prost(string, tag = "7")]
    pub cluster_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub namespace: ::prost::alloc::string::String,
    /// labels in `foo=bar` format.
    #[prost(string, repeated, tag = "4")]
    pub labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub pod_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub workloads: ::prost::alloc::vec::Vec<Workload>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Workload {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tcp {
    #[prost(uint32, tag = "1")]
    pub source_port: u32,
    #[prost(uint32, tag = "2")]
    pub destination_port: u32,
    #[prost(message, optional, tag = "3")]
    pub flags: ::core::option::Option<TcpFlags>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ip {
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    /// source_xlated is the post-translation source IP when the flow was
    /// SNATed. When "source_xlated" is set, the "source" field is populated
    /// with the pre-translation source IP address.
    #[prost(string, tag = "5")]
    pub source_xlated: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub destination: ::prost::alloc::string::String,
    #[prost(enumeration = "IpVersion", tag = "3")]
    pub ip_version: i32,
    /// This field indicates whether the TraceReasonEncryptMask is set or not.
    /// <https://github.com/cilium/cilium/blob/ba0ed147bd5bb342f67b1794c2ad13c6e99d5236/pkg/monitor/datapath_trace.go#L27>
    #[prost(bool, tag = "4")]
    pub encrypted: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ethernet {
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub destination: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TcpFlags {
    #[prost(bool, tag = "1")]
    pub fin: bool,
    #[prost(bool, tag = "2")]
    pub syn: bool,
    #[prost(bool, tag = "3")]
    pub rst: bool,
    #[prost(bool, tag = "4")]
    pub psh: bool,
    #[prost(bool, tag = "5")]
    pub ack: bool,
    #[prost(bool, tag = "6")]
    pub urg: bool,
    #[prost(bool, tag = "7")]
    pub ece: bool,
    #[prost(bool, tag = "8")]
    pub cwr: bool,
    #[prost(bool, tag = "9")]
    pub ns: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Udp {
    #[prost(uint32, tag = "1")]
    pub source_port: u32,
    #[prost(uint32, tag = "2")]
    pub destination_port: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sctp {
    #[prost(uint32, tag = "1")]
    pub source_port: u32,
    #[prost(uint32, tag = "2")]
    pub destination_port: u32,
    #[prost(enumeration = "SctpChunkType", tag = "3")]
    pub chunk_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IcmPv4 {
    #[prost(uint32, tag = "1")]
    pub r#type: u32,
    #[prost(uint32, tag = "2")]
    pub code: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IcmPv6 {
    #[prost(uint32, tag = "1")]
    pub r#type: u32,
    #[prost(uint32, tag = "2")]
    pub code: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vrrp {
    #[prost(uint32, tag = "1")]
    pub r#type: u32,
    #[prost(uint32, tag = "2")]
    pub vrid: u32,
    #[prost(uint32, tag = "3")]
    pub priority: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Igmp {
    #[prost(uint32, tag = "1")]
    pub r#type: u32,
    #[prost(string, tag = "2")]
    pub group_address: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tunnel {
    #[prost(enumeration = "tunnel::Protocol", tag = "1")]
    pub protocol: i32,
    #[prost(message, optional, tag = "2")]
    pub ip: ::core::option::Option<Ip>,
    #[prost(message, optional, tag = "3")]
    pub l4: ::core::option::Option<Layer4>,
    #[prost(uint32, tag = "4")]
    pub vni: u32,
}
/// Nested message and enum types in `Tunnel`.
pub mod tunnel {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Protocol {
        Unknown = 0,
        Vxlan = 1,
        Geneve = 2,
    }
    impl Protocol {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Protocol::Unknown => "UNKNOWN",
                Protocol::Vxlan => "VXLAN",
                Protocol::Geneve => "GENEVE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "VXLAN" => Some(Self::Vxlan),
                "GENEVE" => Some(Self::Geneve),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Policy {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag = "4")]
    pub revision: u64,
    #[prost(string, tag = "5")]
    pub kind: ::prost::alloc::string::String,
}
/// EventTypeFilter is a filter describing a particular event type.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventTypeFilter {
    /// type is the primary flow type as defined by:
    /// github.com/cilium/cilium/pkg/monitor/api.MessageType*
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    /// match_sub_type is set to true when matching on the sub_type should
    /// be done. This flag is required as 0 is a valid sub_type.
    #[prost(bool, tag = "2")]
    pub match_sub_type: bool,
    /// sub_type is the secondary type, e.g.
    /// - github.com/cilium/cilium/pkg/monitor/api.Trace*
    #[prost(int32, tag = "3")]
    pub sub_type: i32,
}
/// CiliumEventType from which the flow originated.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CiliumEventType {
    /// type of event the flow originated from, i.e.
    /// github.com/cilium/cilium/pkg/monitor/api.MessageType*
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    /// sub_type may indicate more details depending on type, e.g.
    /// - github.com/cilium/cilium/pkg/monitor/api.Trace*
    /// - github.com/cilium/cilium/pkg/monitor/api.Drop*
    /// - github.com/cilium/cilium/pkg/monitor/api.DbgCapture*
    #[prost(int32, tag = "2")]
    pub sub_type: i32,
}
/// FlowFilter represent an individual flow filter. All fields are optional. If
/// multiple fields are set, then all fields must match for the filter to match.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FlowFilter {
    /// uuid filters by a list of flow uuids.
    #[prost(string, repeated, tag = "29")]
    pub uuid: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// source_ip filters by a list of source ips. Each of the source ips can be
    /// specified as an exact match (e.g. "1.1.1.1") or as a CIDR range (e.g.
    /// "1.1.1.0/24").
    #[prost(string, repeated, tag = "1")]
    pub source_ip: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// source_ip_xlated filters by a list IPs. Each of the IPs can be specified
    /// as an exact match (e.g. "1.1.1.1") or as a CIDR range (e.g.
    /// "1.1.1.0/24").
    #[prost(string, repeated, tag = "34")]
    pub source_ip_xlated: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// source_pod filters by a list of source pod name prefixes, optionally
    /// within a given namespace (e.g. "xwing", "kube-system/coredns-").
    /// The pod name can be omitted to only filter by namespace
    /// (e.g. "kube-system/") or the namespace can be omitted to filter for
    /// pods in any namespace (e.g. "/xwing")
    #[prost(string, repeated, tag = "2")]
    pub source_pod: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// source_fqdn filters by a list of source fully qualified domain names
    #[prost(string, repeated, tag = "7")]
    pub source_fqdn: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// source_labels filters on a list of source label selectors. Selectors
    /// support the full Kubernetes label selector syntax.
    #[prost(string, repeated, tag = "10")]
    pub source_label: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// source_service filters on a list of source service names. This field
    /// supports the same syntax as the source_pod field.
    #[prost(string, repeated, tag = "16")]
    pub source_service: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// source_workload filters by a list of source workload.
    #[prost(message, repeated, tag = "26")]
    pub source_workload: ::prost::alloc::vec::Vec<Workload>,
    /// source_cluster_name filters by a list of source cluster names.
    #[prost(string, repeated, tag = "37")]
    pub source_cluster_name: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// destination_ip filters by a list of destination ips. Each of the
    /// destination ips can be specified as an exact match (e.g. "1.1.1.1") or
    /// as a CIDR range (e.g. "1.1.1.0/24").
    #[prost(string, repeated, tag = "3")]
    pub destination_ip: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// destination_pod filters by a list of destination pod names
    #[prost(string, repeated, tag = "4")]
    pub destination_pod: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// destination_fqdn filters by a list of destination fully qualified domain names
    #[prost(string, repeated, tag = "8")]
    pub destination_fqdn: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// destination_label filters on a list of destination label selectors
    #[prost(string, repeated, tag = "11")]
    pub destination_label: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// destination_service filters on a list of destination service names
    #[prost(string, repeated, tag = "17")]
    pub destination_service: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// destination_workload filters by a list of destination workload.
    #[prost(message, repeated, tag = "27")]
    pub destination_workload: ::prost::alloc::vec::Vec<Workload>,
    /// destination_cluster_name filters by a list of destination cluster names.
    #[prost(string, repeated, tag = "38")]
    pub destination_cluster_name: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    /// traffic_direction filters flow by direction of the connection, e.g.
    /// ingress or egress.
    #[prost(enumeration = "TrafficDirection", repeated, tag = "30")]
    pub traffic_direction: ::prost::alloc::vec::Vec<i32>,
    /// only return Flows that were classified with a particular verdict.
    #[prost(enumeration = "Verdict", repeated, tag = "5")]
    pub verdict: ::prost::alloc::vec::Vec<i32>,
    /// only applicable to Verdict = DROPPED (e.g. "POLICY_DENIED", "UNSUPPORTED_L3_PROTOCOL")
    #[prost(enumeration = "DropReason", repeated, tag = "33")]
    pub drop_reason_desc: ::prost::alloc::vec::Vec<i32>,
    /// interface is the network interface on which this flow was observed.
    #[prost(message, repeated, tag = "35")]
    pub interface: ::prost::alloc::vec::Vec<NetworkInterface>,
    /// event_type is the list of event types to filter on
    #[prost(message, repeated, tag = "6")]
    pub event_type: ::prost::alloc::vec::Vec<EventTypeFilter>,
    /// http_status_code is a list of string prefixes (e.g. "4+", "404", "5+")
    /// to filter on the HTTP status code
    #[prost(string, repeated, tag = "9")]
    pub http_status_code: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// protocol filters flows by L4 or L7 protocol, e.g. (e.g. "tcp", "http")
    #[prost(string, repeated, tag = "12")]
    pub protocol: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// source_port filters flows by L4 source port
    #[prost(string, repeated, tag = "13")]
    pub source_port: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// destination_port filters flows by L4 destination port
    #[prost(string, repeated, tag = "14")]
    pub destination_port: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// reply filters flows based on the direction of the flow.
    #[prost(bool, repeated, tag = "15")]
    pub reply: ::prost::alloc::vec::Vec<bool>,
    /// dns_query filters L7 DNS flows by query patterns (RE2 regex), e.g. 'kube.*local'.
    #[prost(string, repeated, tag = "18")]
    pub dns_query: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// source_identity filters by the security identity of the source endpoint.
    #[prost(uint32, repeated, tag = "19")]
    pub source_identity: ::prost::alloc::vec::Vec<u32>,
    /// destination_identity filters by the security identity of the destination endpoint.
    #[prost(uint32, repeated, tag = "20")]
    pub destination_identity: ::prost::alloc::vec::Vec<u32>,
    /// GET, POST, PUT, etc. methods. This type of field is well suited for an
    /// enum but every single existing place is using a string already.
    #[prost(string, repeated, tag = "21")]
    pub http_method: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// http_path is a list of regular expressions to filter on the HTTP path.
    #[prost(string, repeated, tag = "22")]
    pub http_path: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// http_url is a list of regular expressions to filter on the HTTP URL.
    #[prost(string, repeated, tag = "31")]
    pub http_url: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// http_header is a list of key:value pairs to filter on the HTTP headers.
    #[prost(message, repeated, tag = "32")]
    pub http_header: ::prost::alloc::vec::Vec<HttpHeader>,
    /// tcp_flags filters flows based on TCP header flags
    #[prost(message, repeated, tag = "23")]
    pub tcp_flags: ::prost::alloc::vec::Vec<TcpFlags>,
    /// node_name is a list of patterns to filter on the node name, e.g. "k8s*",
    /// "test-cluster/*.domain.com", "cluster-name/" etc.
    #[prost(string, repeated, tag = "24")]
    pub node_name: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// node_labels filters on a list of node label selectors. Selectors support
    /// the full Kubernetes label selector syntax.
    #[prost(string, repeated, tag = "36")]
    pub node_labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// filter based on IP version (ipv4 or ipv6)
    #[prost(enumeration = "IpVersion", repeated, tag = "25")]
    pub ip_version: ::prost::alloc::vec::Vec<i32>,
    /// trace_id filters flows by trace ID
    #[prost(string, repeated, tag = "28")]
    pub trace_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// ip_trace_id filters flows by IPTraceID
    #[prost(uint64, repeated, tag = "39")]
    pub ip_trace_id: ::prost::alloc::vec::Vec<u64>,
    /// encrypted filters flows based on encryption status (WireGuard/IPsec).
    /// When set to true, only encrypted flows are returned.
    /// When set to false, only unencrypted flows are returned.
    #[prost(bool, repeated, tag = "40")]
    pub encrypted: ::prost::alloc::vec::Vec<bool>,
    /// experimental contains filters that are not stable yet. Support for
    /// experimental features is always optional and subject to change.
    #[prost(message, optional, tag = "999")]
    pub experimental: ::core::option::Option<flow_filter::Experimental>,
}
/// Nested message and enum types in `FlowFilter`.
pub mod flow_filter {
    /// Experimental contains filters that are not stable yet. Support for
    /// experimental features is always optional and subject to change.
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Experimental {
        /// cel_expression takes a common expression language (CEL) expression
        /// returning a boolean to determine if the filter matched or not.
        /// You can use the `_flow` variable to access fields on the flow using
        /// the flow.Flow protobuf field names.
        /// See <https://github.com/google/cel-spec/blob/v0.14.0/doc/intro.md#introduction>
        /// for more details on CEL and accessing the protobuf fields in CEL.
        /// Using CEL has performance cost compared to other filters, so prefer
        /// using non-CEL filters when possible, and try to specify CEL filters
        /// last in the list of FlowFilters.
        #[prost(string, repeated, tag = "1")]
        pub cel_expression: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
}
/// DNS flow. This is basically directly mapped from Cilium's [LogRecordDNS](<https://github.com/cilium/cilium/blob/04f3889d627774f79e56d14ddbc165b3169e2d01/pkg/proxy/accesslog/record.go#L264>):
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dns {
    /// DNS name that's being looked up: e.g. "isovalent.com."
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    /// List of IP addresses in the DNS response.
    #[prost(string, repeated, tag = "2")]
    pub ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// TTL in the DNS response.
    #[prost(uint32, tag = "3")]
    pub ttl: u32,
    /// List of CNames in the DNS response.
    #[prost(string, repeated, tag = "4")]
    pub cnames: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Corresponds to DNSDataSource defined in:
    ///    <https://github.com/cilium/cilium/blob/04f3889d627774f79e56d14ddbc165b3169e2d01/pkg/proxy/accesslog/record.go#L253>
    #[prost(string, tag = "5")]
    pub observation_source: ::prost::alloc::string::String,
    /// Return code of the DNS request defined in:
    ///    <https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6>
    #[prost(uint32, tag = "6")]
    pub rcode: u32,
    /// String representation of qtypes defined in:
    ///    <https://tools.ietf.org/html/rfc1035#section-3.2.3>
    #[prost(string, repeated, tag = "7")]
    pub qtypes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// String representation of rrtypes defined in:
    /// <https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4>
    #[prost(string, repeated, tag = "8")]
    pub rrtypes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpHeader {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// L7 information for HTTP flows. It corresponds to Cilium's [accesslog.LogRecordHTTP](<https://github.com/cilium/cilium/blob/728c79e427438ab6f8d9375b62fccd6fed4ace3a/pkg/proxy/accesslog/record.go#L206>) type.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Http {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub headers: ::prost::alloc::vec::Vec<HttpHeader>,
}
/// L7 information for Kafka flows. It corresponds to Cilium's [accesslog.LogRecordKafka](<https://github.com/cilium/cilium/blob/728c79e427438ab6f8d9375b62fccd6fed4ace3a/pkg/proxy/accesslog/record.go#L229>) type.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Kafka {
    #[prost(int32, tag = "1")]
    pub error_code: i32,
    #[prost(int32, tag = "2")]
    pub api_version: i32,
    #[prost(string, tag = "3")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub correlation_id: i32,
    #[prost(string, tag = "5")]
    pub topic: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Service {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub namespace: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IpTraceId {
    #[prost(uint64, tag = "1")]
    pub trace_id: u64,
    #[prost(uint32, tag = "2")]
    pub ip_option_type: u32,
}
/// LostEvent is a message which notifies consumers about a loss of events
/// that happened before the events were captured by Hubble.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LostEvent {
    /// source is the location where events got lost.
    #[prost(enumeration = "LostEventSource", tag = "1")]
    pub source: i32,
    /// num_events_lost is the number of events that haven been lost at source.
    #[prost(uint64, tag = "2")]
    pub num_events_lost: u64,
    /// cpu on which the event was lost if the source of lost events is
    /// PERF_EVENT_RING_BUFFER.
    #[prost(message, optional, tag = "3")]
    pub cpu: ::core::option::Option<i32>,
    /// first is the timestamp of the first event that was lost.
    #[prost(message, optional, tag = "4")]
    pub first: ::core::option::Option<::prost_types::Timestamp>,
    /// last is the timestamp of the last event that was lost.
    #[prost(message, optional, tag = "5")]
    pub last: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentEvent {
    #[prost(enumeration = "AgentEventType", tag = "1")]
    pub r#type: i32,
    #[prost(
        oneof = "agent_event::Notification",
        tags = "100, 101, 102, 103, 104, 105, 106, 107"
    )]
    pub notification: ::core::option::Option<agent_event::Notification>,
}
/// Nested message and enum types in `AgentEvent`.
pub mod agent_event {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Notification {
        #[prost(message, tag = "100")]
        Unknown(super::AgentEventUnknown),
        #[prost(message, tag = "101")]
        AgentStart(super::TimeNotification),
        /// used for POLICY_UPDATED and POLICY_DELETED
        #[prost(message, tag = "102")]
        PolicyUpdate(super::PolicyUpdateNotification),
        /// used for ENDPOINT_REGENERATE_SUCCESS and ENDPOINT_REGENERATE_FAILURE
        #[prost(message, tag = "103")]
        EndpointRegenerate(super::EndpointRegenNotification),
        /// used for ENDPOINT_CREATED and ENDPOINT_DELETED
        #[prost(message, tag = "104")]
        EndpointUpdate(super::EndpointUpdateNotification),
        /// used for IPCACHE_UPSERTED and IPCACHE_DELETED
        #[prost(message, tag = "105")]
        IpcacheUpdate(super::IpCacheNotification),
        #[prost(message, tag = "106")]
        ServiceUpsert(super::ServiceUpsertNotification),
        #[prost(message, tag = "107")]
        ServiceDelete(super::ServiceDeleteNotification),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentEventUnknown {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub notification: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeNotification {
    #[prost(message, optional, tag = "1")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PolicyUpdateNotification {
    #[prost(string, repeated, tag = "1")]
    pub labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag = "2")]
    pub revision: u64,
    #[prost(int64, tag = "3")]
    pub rule_count: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EndpointRegenNotification {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, repeated, tag = "2")]
    pub labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EndpointUpdateNotification {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, repeated, tag = "2")]
    pub labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub pod_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub namespace: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IpCacheNotification {
    #[prost(string, tag = "1")]
    pub cidr: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub identity: u32,
    #[prost(message, optional, tag = "3")]
    pub old_identity: ::core::option::Option<u32>,
    #[prost(string, tag = "4")]
    pub host_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub old_host_ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "6")]
    pub encrypt_key: u32,
    #[prost(string, tag = "7")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub pod_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceUpsertNotificationAddr {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceUpsertNotification {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(message, optional, tag = "2")]
    pub frontend_address: ::core::option::Option<ServiceUpsertNotificationAddr>,
    #[prost(message, repeated, tag = "3")]
    pub backend_addresses: ::prost::alloc::vec::Vec<ServiceUpsertNotificationAddr>,
    #[prost(string, tag = "4")]
    pub r#type: ::prost::alloc::string::String,
    #[deprecated]
    #[prost(string, tag = "5")]
    pub traffic_policy: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub ext_traffic_policy: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub int_traffic_policy: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceDeleteNotification {
    #[prost(uint32, tag = "1")]
    pub id: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NetworkInterface {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DebugEvent {
    #[prost(enumeration = "DebugEventType", tag = "1")]
    pub r#type: i32,
    #[prost(message, optional, tag = "2")]
    pub source: ::core::option::Option<Endpoint>,
    #[prost(message, optional, tag = "3")]
    pub hash: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "4")]
    pub arg1: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "5")]
    pub arg2: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "6")]
    pub arg3: ::core::option::Option<u32>,
    #[prost(string, tag = "7")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub cpu: ::core::option::Option<i32>,
}
/// Aggregate contains flow aggregation counters
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Aggregate {
    /// ingress_flow_count is the count of flows in the ingress direction
    #[prost(uint32, tag = "1")]
    pub ingress_flow_count: u32,
    /// egress_flow_count is the count of flows in the egress direction
    #[prost(uint32, tag = "2")]
    pub egress_flow_count: u32,
    /// unknown_direction_flow_count is the count of flows with unknown traffic direction
    #[prost(uint32, tag = "3")]
    pub unknown_direction_flow_count: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FlowType {
    UnknownType = 0,
    /// not sure about the underscore here, but `L34` also reads strange
    L3L4 = 1,
    L7 = 2,
    Sock = 3,
}
impl FlowType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FlowType::UnknownType => "UNKNOWN_TYPE",
            FlowType::L3L4 => "L3_L4",
            FlowType::L7 => "L7",
            FlowType::Sock => "SOCK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_TYPE" => Some(Self::UnknownType),
            "L3_L4" => Some(Self::L3L4),
            "L7" => Some(Self::L7),
            "SOCK" => Some(Self::Sock),
            _ => None,
        }
    }
}
/// These types correspond to definitions in pkg/policy/l4.go.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AuthType {
    Disabled = 0,
    Spire = 1,
    TestAlwaysFail = 2,
}
impl AuthType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            AuthType::Disabled => "DISABLED",
            AuthType::Spire => "SPIRE",
            AuthType::TestAlwaysFail => "TEST_ALWAYS_FAIL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DISABLED" => Some(Self::Disabled),
            "SPIRE" => Some(Self::Spire),
            "TEST_ALWAYS_FAIL" => Some(Self::TestAlwaysFail),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TraceObservationPoint {
    /// Cilium treats 0 as TO_LXC, but its's something we should work to remove.
    /// This is intentionally set as unknown, so proto API can guarantee the
    /// observation point is always going to be present on trace events.
    UnknownPoint = 0,
    /// TO_PROXY indicates network packets are transmitted towards the l7 proxy.
    ToProxy = 1,
    /// TO_HOST indicates network packets are transmitted towards the host
    /// namespace.
    ToHost = 2,
    /// TO_STACK indicates network packets are transmitted towards the Linux
    /// kernel network stack on host machine.
    ToStack = 3,
    /// TO_OVERLAY indicates network packets are transmitted towards the tunnel
    /// device.
    ToOverlay = 4,
    /// TO_ENDPOINT indicates network packets are transmitted towards endpoints
    /// (containers).
    ToEndpoint = 101,
    /// FROM_ENDPOINT indicates network packets were received from endpoints
    /// (containers).
    FromEndpoint = 5,
    /// FROM_PROXY indicates network packets were received from the l7 proxy.
    FromProxy = 6,
    /// FROM_HOST indicates network packets were received from the host
    /// namespace.
    FromHost = 7,
    /// FROM_STACK indicates network packets were received from the Linux kernel
    /// network stack on host machine.
    FromStack = 8,
    /// FROM_OVERLAY indicates network packets were received from the tunnel
    /// device.
    FromOverlay = 9,
    /// FROM_NETWORK indicates network packets were received from native
    /// devices.
    FromNetwork = 10,
    /// TO_NETWORK indicates network packets are transmitted towards native
    /// devices.
    ToNetwork = 11,
    /// FROM_CRYPTO indicates network packets were received from the crypto
    /// process for decryption.
    FromCrypto = 12,
    /// TO_CRYPTO indicates network packets are transmitted towards the crypto
    /// process for encryption.
    ToCrypto = 13,
}
impl TraceObservationPoint {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TraceObservationPoint::UnknownPoint => "UNKNOWN_POINT",
            TraceObservationPoint::ToProxy => "TO_PROXY",
            TraceObservationPoint::ToHost => "TO_HOST",
            TraceObservationPoint::ToStack => "TO_STACK",
            TraceObservationPoint::ToOverlay => "TO_OVERLAY",
            TraceObservationPoint::ToEndpoint => "TO_ENDPOINT",
            TraceObservationPoint::FromEndpoint => "FROM_ENDPOINT",
            TraceObservationPoint::FromProxy => "FROM_PROXY",
            TraceObservationPoint::FromHost => "FROM_HOST",
            TraceObservationPoint::FromStack => "FROM_STACK",
            TraceObservationPoint::FromOverlay => "FROM_OVERLAY",
            TraceObservationPoint::FromNetwork => "FROM_NETWORK",
            TraceObservationPoint::ToNetwork => "TO_NETWORK",
            TraceObservationPoint::FromCrypto => "FROM_CRYPTO",
            TraceObservationPoint::ToCrypto => "TO_CRYPTO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_POINT" => Some(Self::UnknownPoint),
            "TO_PROXY" => Some(Self::ToProxy),
            "TO_HOST" => Some(Self::ToHost),
            "TO_STACK" => Some(Self::ToStack),
            "TO_OVERLAY" => Some(Self::ToOverlay),
            "TO_ENDPOINT" => Some(Self::ToEndpoint),
            "FROM_ENDPOINT" => Some(Self::FromEndpoint),
            "FROM_PROXY" => Some(Self::FromProxy),
            "FROM_HOST" => Some(Self::FromHost),
            "FROM_STACK" => Some(Self::FromStack),
            "FROM_OVERLAY" => Some(Self::FromOverlay),
            "FROM_NETWORK" => Some(Self::FromNetwork),
            "TO_NETWORK" => Some(Self::ToNetwork),
            "FROM_CRYPTO" => Some(Self::FromCrypto),
            "TO_CRYPTO" => Some(Self::ToCrypto),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TraceReason {
    Unknown = 0,
    New = 1,
    Established = 2,
    Reply = 3,
    Related = 4,
    Reopened = 5,
    Srv6Encap = 6,
    Srv6Decap = 7,
    EncryptOverlay = 8,
}
impl TraceReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TraceReason::Unknown => "TRACE_REASON_UNKNOWN",
            TraceReason::New => "NEW",
            TraceReason::Established => "ESTABLISHED",
            TraceReason::Reply => "REPLY",
            TraceReason::Related => "RELATED",
            TraceReason::Reopened => "REOPENED",
            TraceReason::Srv6Encap => "SRV6_ENCAP",
            TraceReason::Srv6Decap => "SRV6_DECAP",
            TraceReason::EncryptOverlay => "ENCRYPT_OVERLAY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRACE_REASON_UNKNOWN" => Some(Self::Unknown),
            "NEW" => Some(Self::New),
            "ESTABLISHED" => Some(Self::Established),
            "REPLY" => Some(Self::Reply),
            "RELATED" => Some(Self::Related),
            "REOPENED" => Some(Self::Reopened),
            "SRV6_ENCAP" => Some(Self::Srv6Encap),
            "SRV6_DECAP" => Some(Self::Srv6Decap),
            "ENCRYPT_OVERLAY" => Some(Self::EncryptOverlay),
            _ => None,
        }
    }
}
/// This enum corresponds to Cilium's L7 accesslog [FlowType](<https://github.com/cilium/cilium/blob/728c79e427438ab6f8d9375b62fccd6fed4ace3a/pkg/proxy/accesslog/record.go#L26>):
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum L7FlowType {
    UnknownL7Type = 0,
    Request = 1,
    Response = 2,
    Sample = 3,
}
impl L7FlowType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            L7FlowType::UnknownL7Type => "UNKNOWN_L7_TYPE",
            L7FlowType::Request => "REQUEST",
            L7FlowType::Response => "RESPONSE",
            L7FlowType::Sample => "SAMPLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_L7_TYPE" => Some(Self::UnknownL7Type),
            "REQUEST" => Some(Self::Request),
            "RESPONSE" => Some(Self::Response),
            "SAMPLE" => Some(Self::Sample),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SctpChunkType {
    Unsupported = 0,
    Init = 1,
    InitAck = 2,
    Shutdown = 3,
    ShutdownAck = 4,
    ShutdownComplete = 5,
    Abort = 6,
}
impl SctpChunkType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            SctpChunkType::Unsupported => "UNSUPPORTED",
            SctpChunkType::Init => "INIT",
            SctpChunkType::InitAck => "INIT_ACK",
            SctpChunkType::Shutdown => "SHUTDOWN",
            SctpChunkType::ShutdownAck => "SHUTDOWN_ACK",
            SctpChunkType::ShutdownComplete => "SHUTDOWN_COMPLETE",
            SctpChunkType::Abort => "ABORT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSUPPORTED" => Some(Self::Unsupported),
            "INIT" => Some(Self::Init),
            "INIT_ACK" => Some(Self::InitAck),
            "SHUTDOWN" => Some(Self::Shutdown),
            "SHUTDOWN_ACK" => Some(Self::ShutdownAck),
            "SHUTDOWN_COMPLETE" => Some(Self::ShutdownComplete),
            "ABORT" => Some(Self::Abort),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum IpVersion {
    IpNotUsed = 0,
    IPv4 = 1,
    IPv6 = 2,
}
impl IpVersion {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            IpVersion::IpNotUsed => "IP_NOT_USED",
            IpVersion::IPv4 => "IPv4",
            IpVersion::IPv6 => "IPv6",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "IP_NOT_USED" => Some(Self::IpNotUsed),
            "IPv4" => Some(Self::IPv4),
            "IPv6" => Some(Self::IPv6),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Verdict {
    /// UNKNOWN is used if there is no verdict for this flow event
    Unknown = 0,
    /// FORWARDED is used for flow events where the trace point has forwarded
    /// this packet or connection to the next processing entity.
    Forwarded = 1,
    /// DROPPED is used for flow events where the connection or packet has
    /// been dropped (e.g. due to a malformed packet, it being rejected by a
    /// network policy etc). The exact drop reason may be found in drop_reason_desc.
    Dropped = 2,
    /// ERROR is used for flow events where an error occurred during processing
    Error = 3,
    /// AUDIT is used on policy verdict events in policy audit mode, to
    /// denominate flows that would have been dropped by policy if audit mode
    /// was turned off
    Audit = 4,
    /// REDIRECTED is used for flow events which have been redirected to the proxy
    Redirected = 5,
    /// TRACED is used for flow events which have been observed at a trace point,
    /// but no particular verdict has been reached yet
    Traced = 6,
    /// TRANSLATED is used for flow events where an address has been translated
    Translated = 7,
}
impl Verdict {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Verdict::Unknown => "VERDICT_UNKNOWN",
            Verdict::Forwarded => "FORWARDED",
            Verdict::Dropped => "DROPPED",
            Verdict::Error => "ERROR",
            Verdict::Audit => "AUDIT",
            Verdict::Redirected => "REDIRECTED",
            Verdict::Traced => "TRACED",
            Verdict::Translated => "TRANSLATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VERDICT_UNKNOWN" => Some(Self::Unknown),
            "FORWARDED" => Some(Self::Forwarded),
            "DROPPED" => Some(Self::Dropped),
            "ERROR" => Some(Self::Error),
            "AUDIT" => Some(Self::Audit),
            "REDIRECTED" => Some(Self::Redirected),
            "TRACED" => Some(Self::Traced),
            "TRANSLATED" => Some(Self::Translated),
            _ => None,
        }
    }
}
/// These values are shared with pkg/monitor/api/drop.go and bpf/lib/common.h.
/// Note that non-drop reasons (i.e. values less than api.DropMin) are not used
/// here.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DropReason {
    /// non-drop reasons
    Unknown = 0,
    /// drop reasons
    InvalidSourceMac = 130,
    InvalidDestinationMac = 131,
    InvalidSourceIp = 132,
    PolicyDenied = 133,
    InvalidPacketDropped = 134,
    CtTruncatedOrInvalidHeader = 135,
    CtMissingTcpAckFlag = 136,
    CtUnknownL4Protocol = 137,
    CtCannotCreateEntryFromPacket = 138,
    UnsupportedL3Protocol = 139,
    MissedTailCall = 140,
    ErrorWritingToPacket = 141,
    UnknownL4Protocol = 142,
    UnknownIcmpv4Code = 143,
    UnknownIcmpv4Type = 144,
    UnknownIcmpv6Code = 145,
    UnknownIcmpv6Type = 146,
    ErrorRetrievingTunnelKey = 147,
    ErrorRetrievingTunnelOptions = 148,
    InvalidGeneveOption = 149,
    UnknownL3TargetAddress = 150,
    StaleOrUnroutableIp = 151,
    NoMatchingLocalContainerFound = 152,
    ErrorWhileCorrectingL3Checksum = 153,
    ErrorWhileCorrectingL4Checksum = 154,
    CtMapInsertionFailed = 155,
    InvalidIpv6ExtensionHeader = 156,
    IpFragmentationNotSupported = 157,
    ServiceBackendNotFound = 158,
    NoTunnelOrEncapsulationEndpoint = 160,
    FailedToInsertIntoProxymap = 161,
    ReachedEdtRateLimitingDropHorizon = 162,
    UnknownConnectionTrackingState = 163,
    LocalHostIsUnreachable = 164,
    NoConfigurationAvailableToPerformPolicyDecision = 165,
    UnsupportedL2Protocol = 166,
    NoMappingForNatMasquerade = 167,
    UnsupportedProtocolForNatMasquerade = 168,
    FibLookupFailed = 169,
    EncapsulationTrafficIsProhibited = 170,
    InvalidIdentity = 171,
    UnknownSender = 172,
    NatNotNeeded = 173,
    IsAClusterip = 174,
    FirstLogicalDatagramFragmentNotFound = 175,
    ForbiddenIcmpv6Message = 176,
    DeniedByLbSrcRangeCheck = 177,
    SocketLookupFailed = 178,
    SocketAssignFailed = 179,
    ProxyRedirectionNotSupportedForProtocol = 180,
    PolicyDeny = 181,
    VlanFiltered = 182,
    InvalidVni = 183,
    InvalidTcBuffer = 184,
    NoSid = 185,
    MissingSrv6State = 186,
    Nat46 = 187,
    Nat64 = 188,
    AuthRequired = 189,
    CtNoMapFound = 190,
    SnatNoMapFound = 191,
    InvalidClusterId = 192,
    UnsupportedProtocolForDsrEncap = 193,
    NoEgressGateway = 194,
    UnencryptedTraffic = 195,
    TtlExceeded = 196,
    NoNodeId = 197,
    DropRateLimited = 198,
    IgmpHandled = 199,
    IgmpSubscribed = 200,
    MulticastHandled = 201,
    /// A BPF program wants to tail call into bpf_host, but the host datapath
    /// hasn't been loaded yet.
    DropHostNotReady = 202,
    /// A BPF program wants to tail call some endpoint's policy program in
    /// cilium_call_policy, but the program is not available.
    DropEpNotReady = 203,
    /// An Egress Gateway node matched a packet against an Egress Gateway policy
    /// that didn't select a valid Egress IP.
    DropNoEgressIp = 204,
    /// Punt packet to a user space proxy.
    DropPuntProxy = 205,
    /// A BPF program failed to look up information for a network device.
    DropNoDevice = 206,
}
impl DropReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DropReason::Unknown => "DROP_REASON_UNKNOWN",
            DropReason::InvalidSourceMac => "INVALID_SOURCE_MAC",
            DropReason::InvalidDestinationMac => "INVALID_DESTINATION_MAC",
            DropReason::InvalidSourceIp => "INVALID_SOURCE_IP",
            DropReason::PolicyDenied => "POLICY_DENIED",
            DropReason::InvalidPacketDropped => "INVALID_PACKET_DROPPED",
            DropReason::CtTruncatedOrInvalidHeader => "CT_TRUNCATED_OR_INVALID_HEADER",
            DropReason::CtMissingTcpAckFlag => "CT_MISSING_TCP_ACK_FLAG",
            DropReason::CtUnknownL4Protocol => "CT_UNKNOWN_L4_PROTOCOL",
            DropReason::CtCannotCreateEntryFromPacket => {
                "CT_CANNOT_CREATE_ENTRY_FROM_PACKET"
            }
            DropReason::UnsupportedL3Protocol => "UNSUPPORTED_L3_PROTOCOL",
            DropReason::MissedTailCall => "MISSED_TAIL_CALL",
            DropReason::ErrorWritingToPacket => "ERROR_WRITING_TO_PACKET",
            DropReason::UnknownL4Protocol => "UNKNOWN_L4_PROTOCOL",
            DropReason::UnknownIcmpv4Code => "UNKNOWN_ICMPV4_CODE",
            DropReason::UnknownIcmpv4Type => "UNKNOWN_ICMPV4_TYPE",
            DropReason::UnknownIcmpv6Code => "UNKNOWN_ICMPV6_CODE",
            DropReason::UnknownIcmpv6Type => "UNKNOWN_ICMPV6_TYPE",
            DropReason::ErrorRetrievingTunnelKey => "ERROR_RETRIEVING_TUNNEL_KEY",
            DropReason::ErrorRetrievingTunnelOptions => "ERROR_RETRIEVING_TUNNEL_OPTIONS",
            DropReason::InvalidGeneveOption => "INVALID_GENEVE_OPTION",
            DropReason::UnknownL3TargetAddress => "UNKNOWN_L3_TARGET_ADDRESS",
            DropReason::StaleOrUnroutableIp => "STALE_OR_UNROUTABLE_IP",
            DropReason::NoMatchingLocalContainerFound => {
                "NO_MATCHING_LOCAL_CONTAINER_FOUND"
            }
            DropReason::ErrorWhileCorrectingL3Checksum => {
                "ERROR_WHILE_CORRECTING_L3_CHECKSUM"
            }
            DropReason::ErrorWhileCorrectingL4Checksum => {
                "ERROR_WHILE_CORRECTING_L4_CHECKSUM"
            }
            DropReason::CtMapInsertionFailed => "CT_MAP_INSERTION_FAILED",
            DropReason::InvalidIpv6ExtensionHeader => "INVALID_IPV6_EXTENSION_HEADER",
            DropReason::IpFragmentationNotSupported => "IP_FRAGMENTATION_NOT_SUPPORTED",
            DropReason::ServiceBackendNotFound => "SERVICE_BACKEND_NOT_FOUND",
            DropReason::NoTunnelOrEncapsulationEndpoint => {
                "NO_TUNNEL_OR_ENCAPSULATION_ENDPOINT"
            }
            DropReason::FailedToInsertIntoProxymap => "FAILED_TO_INSERT_INTO_PROXYMAP",
            DropReason::ReachedEdtRateLimitingDropHorizon => {
                "REACHED_EDT_RATE_LIMITING_DROP_HORIZON"
            }
            DropReason::UnknownConnectionTrackingState => {
                "UNKNOWN_CONNECTION_TRACKING_STATE"
            }
            DropReason::LocalHostIsUnreachable => "LOCAL_HOST_IS_UNREACHABLE",
            DropReason::NoConfigurationAvailableToPerformPolicyDecision => {
                "NO_CONFIGURATION_AVAILABLE_TO_PERFORM_POLICY_DECISION"
            }
            DropReason::UnsupportedL2Protocol => "UNSUPPORTED_L2_PROTOCOL",
            DropReason::NoMappingForNatMasquerade => "NO_MAPPING_FOR_NAT_MASQUERADE",
            DropReason::UnsupportedProtocolForNatMasquerade => {
                "UNSUPPORTED_PROTOCOL_FOR_NAT_MASQUERADE"
            }
            DropReason::FibLookupFailed => "FIB_LOOKUP_FAILED",
            DropReason::EncapsulationTrafficIsProhibited => {
                "ENCAPSULATION_TRAFFIC_IS_PROHIBITED"
            }
            DropReason::InvalidIdentity => "INVALID_IDENTITY",
            DropReason::UnknownSender => "UNKNOWN_SENDER",
            DropReason::NatNotNeeded => "NAT_NOT_NEEDED",
            DropReason::IsAClusterip => "IS_A_CLUSTERIP",
            DropReason::FirstLogicalDatagramFragmentNotFound => {
                "FIRST_LOGICAL_DATAGRAM_FRAGMENT_NOT_FOUND"
            }
            DropReason::ForbiddenIcmpv6Message => "FORBIDDEN_ICMPV6_MESSAGE",
            DropReason::DeniedByLbSrcRangeCheck => "DENIED_BY_LB_SRC_RANGE_CHECK",
            DropReason::SocketLookupFailed => "SOCKET_LOOKUP_FAILED",
            DropReason::SocketAssignFailed => "SOCKET_ASSIGN_FAILED",
            DropReason::ProxyRedirectionNotSupportedForProtocol => {
                "PROXY_REDIRECTION_NOT_SUPPORTED_FOR_PROTOCOL"
            }
            DropReason::PolicyDeny => "POLICY_DENY",
            DropReason::VlanFiltered => "VLAN_FILTERED",
            DropReason::InvalidVni => "INVALID_VNI",
            DropReason::InvalidTcBuffer => "INVALID_TC_BUFFER",
            DropReason::NoSid => "NO_SID",
            DropReason::MissingSrv6State => "MISSING_SRV6_STATE",
            DropReason::Nat46 => "NAT46",
            DropReason::Nat64 => "NAT64",
            DropReason::AuthRequired => "AUTH_REQUIRED",
            DropReason::CtNoMapFound => "CT_NO_MAP_FOUND",
            DropReason::SnatNoMapFound => "SNAT_NO_MAP_FOUND",
            DropReason::InvalidClusterId => "INVALID_CLUSTER_ID",
            DropReason::UnsupportedProtocolForDsrEncap => {
                "UNSUPPORTED_PROTOCOL_FOR_DSR_ENCAP"
            }
            DropReason::NoEgressGateway => "NO_EGRESS_GATEWAY",
            DropReason::UnencryptedTraffic => "UNENCRYPTED_TRAFFIC",
            DropReason::TtlExceeded => "TTL_EXCEEDED",
            DropReason::NoNodeId => "NO_NODE_ID",
            DropReason::DropRateLimited => "DROP_RATE_LIMITED",
            DropReason::IgmpHandled => "IGMP_HANDLED",
            DropReason::IgmpSubscribed => "IGMP_SUBSCRIBED",
            DropReason::MulticastHandled => "MULTICAST_HANDLED",
            DropReason::DropHostNotReady => "DROP_HOST_NOT_READY",
            DropReason::DropEpNotReady => "DROP_EP_NOT_READY",
            DropReason::DropNoEgressIp => "DROP_NO_EGRESS_IP",
            DropReason::DropPuntProxy => "DROP_PUNT_PROXY",
            DropReason::DropNoDevice => "DROP_NO_DEVICE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DROP_REASON_UNKNOWN" => Some(Self::Unknown),
            "INVALID_SOURCE_MAC" => Some(Self::InvalidSourceMac),
            "INVALID_DESTINATION_MAC" => Some(Self::InvalidDestinationMac),
            "INVALID_SOURCE_IP" => Some(Self::InvalidSourceIp),
            "POLICY_DENIED" => Some(Self::PolicyDenied),
            "INVALID_PACKET_DROPPED" => Some(Self::InvalidPacketDropped),
            "CT_TRUNCATED_OR_INVALID_HEADER" => Some(Self::CtTruncatedOrInvalidHeader),
            "CT_MISSING_TCP_ACK_FLAG" => Some(Self::CtMissingTcpAckFlag),
            "CT_UNKNOWN_L4_PROTOCOL" => Some(Self::CtUnknownL4Protocol),
            "CT_CANNOT_CREATE_ENTRY_FROM_PACKET" => {
                Some(Self::CtCannotCreateEntryFromPacket)
            }
            "UNSUPPORTED_L3_PROTOCOL" => Some(Self::UnsupportedL3Protocol),
            "MISSED_TAIL_CALL" => Some(Self::MissedTailCall),
            "ERROR_WRITING_TO_PACKET" => Some(Self::ErrorWritingToPacket),
            "UNKNOWN_L4_PROTOCOL" => Some(Self::UnknownL4Protocol),
            "UNKNOWN_ICMPV4_CODE" => Some(Self::UnknownIcmpv4Code),
            "UNKNOWN_ICMPV4_TYPE" => Some(Self::UnknownIcmpv4Type),
            "UNKNOWN_ICMPV6_CODE" => Some(Self::UnknownIcmpv6Code),
            "UNKNOWN_ICMPV6_TYPE" => Some(Self::UnknownIcmpv6Type),
            "ERROR_RETRIEVING_TUNNEL_KEY" => Some(Self::ErrorRetrievingTunnelKey),
            "ERROR_RETRIEVING_TUNNEL_OPTIONS" => Some(Self::ErrorRetrievingTunnelOptions),
            "INVALID_GENEVE_OPTION" => Some(Self::InvalidGeneveOption),
            "UNKNOWN_L3_TARGET_ADDRESS" => Some(Self::UnknownL3TargetAddress),
            "STALE_OR_UNROUTABLE_IP" => Some(Self::StaleOrUnroutableIp),
            "NO_MATCHING_LOCAL_CONTAINER_FOUND" => {
                Some(Self::NoMatchingLocalContainerFound)
            }
            "ERROR_WHILE_CORRECTING_L3_CHECKSUM" => {
                Some(Self::ErrorWhileCorrectingL3Checksum)
            }
            "ERROR_WHILE_CORRECTING_L4_CHECKSUM" => {
                Some(Self::ErrorWhileCorrectingL4Checksum)
            }
            "CT_MAP_INSERTION_FAILED" => Some(Self::CtMapInsertionFailed),
            "INVALID_IPV6_EXTENSION_HEADER" => Some(Self::InvalidIpv6ExtensionHeader),
            "IP_FRAGMENTATION_NOT_SUPPORTED" => Some(Self::IpFragmentationNotSupported),
            "SERVICE_BACKEND_NOT_FOUND" => Some(Self::ServiceBackendNotFound),
            "NO_TUNNEL_OR_ENCAPSULATION_ENDPOINT" => {
                Some(Self::NoTunnelOrEncapsulationEndpoint)
            }
            "FAILED_TO_INSERT_INTO_PROXYMAP" => Some(Self::FailedToInsertIntoProxymap),
            "REACHED_EDT_RATE_LIMITING_DROP_HORIZON" => {
                Some(Self::ReachedEdtRateLimitingDropHorizon)
            }
            "UNKNOWN_CONNECTION_TRACKING_STATE" => {
                Some(Self::UnknownConnectionTrackingState)
            }
            "LOCAL_HOST_IS_UNREACHABLE" => Some(Self::LocalHostIsUnreachable),
            "NO_CONFIGURATION_AVAILABLE_TO_PERFORM_POLICY_DECISION" => {
                Some(Self::NoConfigurationAvailableToPerformPolicyDecision)
            }
            "UNSUPPORTED_L2_PROTOCOL" => Some(Self::UnsupportedL2Protocol),
            "NO_MAPPING_FOR_NAT_MASQUERADE" => Some(Self::NoMappingForNatMasquerade),
            "UNSUPPORTED_PROTOCOL_FOR_NAT_MASQUERADE" => {
                Some(Self::UnsupportedProtocolForNatMasquerade)
            }
            "FIB_LOOKUP_FAILED" => Some(Self::FibLookupFailed),
            "ENCAPSULATION_TRAFFIC_IS_PROHIBITED" => {
                Some(Self::EncapsulationTrafficIsProhibited)
            }
            "INVALID_IDENTITY" => Some(Self::InvalidIdentity),
            "UNKNOWN_SENDER" => Some(Self::UnknownSender),
            "NAT_NOT_NEEDED" => Some(Self::NatNotNeeded),
            "IS_A_CLUSTERIP" => Some(Self::IsAClusterip),
            "FIRST_LOGICAL_DATAGRAM_FRAGMENT_NOT_FOUND" => {
                Some(Self::FirstLogicalDatagramFragmentNotFound)
            }
            "FORBIDDEN_ICMPV6_MESSAGE" => Some(Self::ForbiddenIcmpv6Message),
            "DENIED_BY_LB_SRC_RANGE_CHECK" => Some(Self::DeniedByLbSrcRangeCheck),
            "SOCKET_LOOKUP_FAILED" => Some(Self::SocketLookupFailed),
            "SOCKET_ASSIGN_FAILED" => Some(Self::SocketAssignFailed),
            "PROXY_REDIRECTION_NOT_SUPPORTED_FOR_PROTOCOL" => {
                Some(Self::ProxyRedirectionNotSupportedForProtocol)
            }
            "POLICY_DENY" => Some(Self::PolicyDeny),
            "VLAN_FILTERED" => Some(Self::VlanFiltered),
            "INVALID_VNI" => Some(Self::InvalidVni),
            "INVALID_TC_BUFFER" => Some(Self::InvalidTcBuffer),
            "NO_SID" => Some(Self::NoSid),
            "MISSING_SRV6_STATE" => Some(Self::MissingSrv6State),
            "NAT46" => Some(Self::Nat46),
            "NAT64" => Some(Self::Nat64),
            "AUTH_REQUIRED" => Some(Self::AuthRequired),
            "CT_NO_MAP_FOUND" => Some(Self::CtNoMapFound),
            "SNAT_NO_MAP_FOUND" => Some(Self::SnatNoMapFound),
            "INVALID_CLUSTER_ID" => Some(Self::InvalidClusterId),
            "UNSUPPORTED_PROTOCOL_FOR_DSR_ENCAP" => {
                Some(Self::UnsupportedProtocolForDsrEncap)
            }
            "NO_EGRESS_GATEWAY" => Some(Self::NoEgressGateway),
            "UNENCRYPTED_TRAFFIC" => Some(Self::UnencryptedTraffic),
            "TTL_EXCEEDED" => Some(Self::TtlExceeded),
            "NO_NODE_ID" => Some(Self::NoNodeId),
            "DROP_RATE_LIMITED" => Some(Self::DropRateLimited),
            "IGMP_HANDLED" => Some(Self::IgmpHandled),
            "IGMP_SUBSCRIBED" => Some(Self::IgmpSubscribed),
            "MULTICAST_HANDLED" => Some(Self::MulticastHandled),
            "DROP_HOST_NOT_READY" => Some(Self::DropHostNotReady),
            "DROP_EP_NOT_READY" => Some(Self::DropEpNotReady),
            "DROP_NO_EGRESS_IP" => Some(Self::DropNoEgressIp),
            "DROP_PUNT_PROXY" => Some(Self::DropPuntProxy),
            "DROP_NO_DEVICE" => Some(Self::DropNoDevice),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TrafficDirection {
    Unknown = 0,
    Ingress = 1,
    Egress = 2,
}
impl TrafficDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TrafficDirection::Unknown => "TRAFFIC_DIRECTION_UNKNOWN",
            TrafficDirection::Ingress => "INGRESS",
            TrafficDirection::Egress => "EGRESS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRAFFIC_DIRECTION_UNKNOWN" => Some(Self::Unknown),
            "INGRESS" => Some(Self::Ingress),
            "EGRESS" => Some(Self::Egress),
            _ => None,
        }
    }
}
/// These values are shared with pkg/monitor/api/datapath_debug.go and bpf/lib/dbg.h.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DebugCapturePoint {
    DbgCapturePointUnknown = 0,
    DbgCaptureDelivery = 4,
    DbgCaptureFromLb = 5,
    DbgCaptureAfterV46 = 6,
    DbgCaptureAfterV64 = 7,
    DbgCaptureProxyPre = 8,
    DbgCaptureProxyPost = 9,
    DbgCaptureSnatPre = 10,
    DbgCaptureSnatPost = 11,
}
impl DebugCapturePoint {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DebugCapturePoint::DbgCapturePointUnknown => "DBG_CAPTURE_POINT_UNKNOWN",
            DebugCapturePoint::DbgCaptureDelivery => "DBG_CAPTURE_DELIVERY",
            DebugCapturePoint::DbgCaptureFromLb => "DBG_CAPTURE_FROM_LB",
            DebugCapturePoint::DbgCaptureAfterV46 => "DBG_CAPTURE_AFTER_V46",
            DebugCapturePoint::DbgCaptureAfterV64 => "DBG_CAPTURE_AFTER_V64",
            DebugCapturePoint::DbgCaptureProxyPre => "DBG_CAPTURE_PROXY_PRE",
            DebugCapturePoint::DbgCaptureProxyPost => "DBG_CAPTURE_PROXY_POST",
            DebugCapturePoint::DbgCaptureSnatPre => "DBG_CAPTURE_SNAT_PRE",
            DebugCapturePoint::DbgCaptureSnatPost => "DBG_CAPTURE_SNAT_POST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DBG_CAPTURE_POINT_UNKNOWN" => Some(Self::DbgCapturePointUnknown),
            "DBG_CAPTURE_DELIVERY" => Some(Self::DbgCaptureDelivery),
            "DBG_CAPTURE_FROM_LB" => Some(Self::DbgCaptureFromLb),
            "DBG_CAPTURE_AFTER_V46" => Some(Self::DbgCaptureAfterV46),
            "DBG_CAPTURE_AFTER_V64" => Some(Self::DbgCaptureAfterV64),
            "DBG_CAPTURE_PROXY_PRE" => Some(Self::DbgCaptureProxyPre),
            "DBG_CAPTURE_PROXY_POST" => Some(Self::DbgCaptureProxyPost),
            "DBG_CAPTURE_SNAT_PRE" => Some(Self::DbgCaptureSnatPre),
            "DBG_CAPTURE_SNAT_POST" => Some(Self::DbgCaptureSnatPost),
            _ => None,
        }
    }
}
/// EventType are constants are based on the ones from <linux/perf_event.h>.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventType {
    Unknown = 0,
    /// EventSample is equivalent to PERF_RECORD_SAMPLE.
    EventSample = 9,
    /// RecordLost is equivalent to PERF_RECORD_LOST.
    RecordLost = 2,
}
impl EventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            EventType::Unknown => "UNKNOWN",
            EventType::EventSample => "EventSample",
            EventType::RecordLost => "RecordLost",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "EventSample" => Some(Self::EventSample),
            "RecordLost" => Some(Self::RecordLost),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LostEventSource {
    UnknownLostEventSource = 0,
    /// PERF_EVENT_RING_BUFFER indicates that events were dropped in the BPF
    /// perf event ring buffer, indicating that userspace agent did not keep up
    /// with the events produced by the datapath.
    PerfEventRingBuffer = 1,
    /// OBSERVER_EVENTS_QUEUE indicates that events were dropped because the
    /// Hubble events queue was full, indicating that the Hubble observer did
    /// not keep up.
    ObserverEventsQueue = 2,
    /// HUBBLE_RING_BUFFER indicates that the event was dropped because it could
    /// not be read from Hubble's ring buffer in time before being overwritten.
    HubbleRingBuffer = 3,
}
impl LostEventSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            LostEventSource::UnknownLostEventSource => "UNKNOWN_LOST_EVENT_SOURCE",
            LostEventSource::PerfEventRingBuffer => "PERF_EVENT_RING_BUFFER",
            LostEventSource::ObserverEventsQueue => "OBSERVER_EVENTS_QUEUE",
            LostEventSource::HubbleRingBuffer => "HUBBLE_RING_BUFFER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_LOST_EVENT_SOURCE" => Some(Self::UnknownLostEventSource),
            "PERF_EVENT_RING_BUFFER" => Some(Self::PerfEventRingBuffer),
            "OBSERVER_EVENTS_QUEUE" => Some(Self::ObserverEventsQueue),
            "HUBBLE_RING_BUFFER" => Some(Self::HubbleRingBuffer),
            _ => None,
        }
    }
}
/// AgentEventType is the type of agent event. These values are shared with type
/// AgentNotification in pkg/monitor/api/types.go.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AgentEventType {
    AgentEventUnknown = 0,
    AgentStarted = 2,
    PolicyUpdated = 3,
    PolicyDeleted = 4,
    EndpointRegenerateSuccess = 5,
    EndpointRegenerateFailure = 6,
    EndpointCreated = 7,
    EndpointDeleted = 8,
    IpcacheUpserted = 9,
    IpcacheDeleted = 10,
    ServiceUpserted = 11,
    ServiceDeleted = 12,
}
impl AgentEventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            AgentEventType::AgentEventUnknown => "AGENT_EVENT_UNKNOWN",
            AgentEventType::AgentStarted => "AGENT_STARTED",
            AgentEventType::PolicyUpdated => "POLICY_UPDATED",
            AgentEventType::PolicyDeleted => "POLICY_DELETED",
            AgentEventType::EndpointRegenerateSuccess => "ENDPOINT_REGENERATE_SUCCESS",
            AgentEventType::EndpointRegenerateFailure => "ENDPOINT_REGENERATE_FAILURE",
            AgentEventType::EndpointCreated => "ENDPOINT_CREATED",
            AgentEventType::EndpointDeleted => "ENDPOINT_DELETED",
            AgentEventType::IpcacheUpserted => "IPCACHE_UPSERTED",
            AgentEventType::IpcacheDeleted => "IPCACHE_DELETED",
            AgentEventType::ServiceUpserted => "SERVICE_UPSERTED",
            AgentEventType::ServiceDeleted => "SERVICE_DELETED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGENT_EVENT_UNKNOWN" => Some(Self::AgentEventUnknown),
            "AGENT_STARTED" => Some(Self::AgentStarted),
            "POLICY_UPDATED" => Some(Self::PolicyUpdated),
            "POLICY_DELETED" => Some(Self::PolicyDeleted),
            "ENDPOINT_REGENERATE_SUCCESS" => Some(Self::EndpointRegenerateSuccess),
            "ENDPOINT_REGENERATE_FAILURE" => Some(Self::EndpointRegenerateFailure),
            "ENDPOINT_CREATED" => Some(Self::EndpointCreated),
            "ENDPOINT_DELETED" => Some(Self::EndpointDeleted),
            "IPCACHE_UPSERTED" => Some(Self::IpcacheUpserted),
            "IPCACHE_DELETED" => Some(Self::IpcacheDeleted),
            "SERVICE_UPSERTED" => Some(Self::ServiceUpserted),
            "SERVICE_DELETED" => Some(Self::ServiceDeleted),
            _ => None,
        }
    }
}
/// This mirrors enum xlate_point in bpf/lib/trace_sock.h
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SocketTranslationPoint {
    SockXlatePointUnknown = 0,
    /// Pre service translation
    SockXlatePointPreDirectionFwd = 1,
    /// Post service translation
    SockXlatePointPostDirectionFwd = 2,
    /// Pre reverse service translation
    SockXlatePointPreDirectionRev = 3,
    /// Post reverse service translation
    SockXlatePointPostDirectionRev = 4,
}
impl SocketTranslationPoint {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            SocketTranslationPoint::SockXlatePointUnknown => "SOCK_XLATE_POINT_UNKNOWN",
            SocketTranslationPoint::SockXlatePointPreDirectionFwd => {
                "SOCK_XLATE_POINT_PRE_DIRECTION_FWD"
            }
            SocketTranslationPoint::SockXlatePointPostDirectionFwd => {
                "SOCK_XLATE_POINT_POST_DIRECTION_FWD"
            }
            SocketTranslationPoint::SockXlatePointPreDirectionRev => {
                "SOCK_XLATE_POINT_PRE_DIRECTION_REV"
            }
            SocketTranslationPoint::SockXlatePointPostDirectionRev => {
                "SOCK_XLATE_POINT_POST_DIRECTION_REV"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SOCK_XLATE_POINT_UNKNOWN" => Some(Self::SockXlatePointUnknown),
            "SOCK_XLATE_POINT_PRE_DIRECTION_FWD" => {
                Some(Self::SockXlatePointPreDirectionFwd)
            }
            "SOCK_XLATE_POINT_POST_DIRECTION_FWD" => {
                Some(Self::SockXlatePointPostDirectionFwd)
            }
            "SOCK_XLATE_POINT_PRE_DIRECTION_REV" => {
                Some(Self::SockXlatePointPreDirectionRev)
            }
            "SOCK_XLATE_POINT_POST_DIRECTION_REV" => {
                Some(Self::SockXlatePointPostDirectionRev)
            }
            _ => None,
        }
    }
}
/// These values are shared with pkg/monitor/api/datapath_debug.go and bpf/lib/dbg.h.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DebugEventType {
    DbgEventUnknown = 0,
    DbgGeneric = 1,
    DbgLocalDelivery = 2,
    DbgEncap = 3,
    DbgLxcFound = 4,
    DbgPolicyDenied = 5,
    DbgCtLookup = 6,
    DbgCtLookupRev = 7,
    DbgCtMatch = 8,
    DbgCtCreated = 9,
    DbgCtCreated2 = 10,
    DbgIcmp6Handle = 11,
    DbgIcmp6Request = 12,
    DbgIcmp6Ns = 13,
    DbgIcmp6TimeExceeded = 14,
    DbgCtVerdict = 15,
    DbgDecap = 16,
    DbgPortMap = 17,
    DbgErrorRet = 18,
    DbgToHost = 19,
    DbgToStack = 20,
    DbgPktHash = 21,
    DbgLb6LookupFrontend = 22,
    DbgLb6LookupFrontendFail = 23,
    DbgLb6LookupBackendSlot = 24,
    DbgLb6LookupBackendSlotSuccess = 25,
    DbgLb6LookupBackendSlotV2Fail = 26,
    DbgLb6LookupBackendFail = 27,
    DbgLb6ReverseNatLookup = 28,
    DbgLb6ReverseNat = 29,
    DbgLb4LookupFrontend = 30,
    DbgLb4LookupFrontendFail = 31,
    DbgLb4LookupBackendSlot = 32,
    DbgLb4LookupBackendSlotSuccess = 33,
    DbgLb4LookupBackendSlotV2Fail = 34,
    DbgLb4LookupBackendFail = 35,
    DbgLb4ReverseNatLookup = 36,
    DbgLb4ReverseNat = 37,
    DbgLb4LoopbackSnat = 38,
    DbgLb4LoopbackSnatRev = 39,
    DbgCtLookup4 = 40,
    DbgRrBackendSlotSel = 41,
    DbgRevProxyLookup = 42,
    DbgRevProxyFound = 43,
    DbgRevProxyUpdate = 44,
    DbgL4Policy = 45,
    DbgNetdevInCluster = 46,
    DbgNetdevEncap4 = 47,
    DbgCtLookup41 = 48,
    DbgCtLookup42 = 49,
    DbgCtCreated4 = 50,
    DbgCtLookup61 = 51,
    DbgCtLookup62 = 52,
    DbgCtCreated6 = 53,
    DbgSkipProxy = 54,
    DbgL4Create = 55,
    DbgIpIdMapFailed4 = 56,
    DbgIpIdMapFailed6 = 57,
    DbgIpIdMapSucceed4 = 58,
    DbgIpIdMapSucceed6 = 59,
    DbgLbStaleCt = 60,
    DbgInheritIdentity = 61,
    DbgSkLookup4 = 62,
    DbgSkLookup6 = 63,
    DbgSkAssign = 64,
    DbgL7Lb = 65,
    DbgSkipPolicy = 66,
    DbgLb6LoopbackSnat = 67,
    DbgLb6LoopbackSnatRev = 68,
}
impl DebugEventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DebugEventType::DbgEventUnknown => "DBG_EVENT_UNKNOWN",
            DebugEventType::DbgGeneric => "DBG_GENERIC",
            DebugEventType::DbgLocalDelivery => "DBG_LOCAL_DELIVERY",
            DebugEventType::DbgEncap => "DBG_ENCAP",
            DebugEventType::DbgLxcFound => "DBG_LXC_FOUND",
            DebugEventType::DbgPolicyDenied => "DBG_POLICY_DENIED",
            DebugEventType::DbgCtLookup => "DBG_CT_LOOKUP",
            DebugEventType::DbgCtLookupRev => "DBG_CT_LOOKUP_REV",
            DebugEventType::DbgCtMatch => "DBG_CT_MATCH",
            DebugEventType::DbgCtCreated => "DBG_CT_CREATED",
            DebugEventType::DbgCtCreated2 => "DBG_CT_CREATED2",
            DebugEventType::DbgIcmp6Handle => "DBG_ICMP6_HANDLE",
            DebugEventType::DbgIcmp6Request => "DBG_ICMP6_REQUEST",
            DebugEventType::DbgIcmp6Ns => "DBG_ICMP6_NS",
            DebugEventType::DbgIcmp6TimeExceeded => "DBG_ICMP6_TIME_EXCEEDED",
            DebugEventType::DbgCtVerdict => "DBG_CT_VERDICT",
            DebugEventType::DbgDecap => "DBG_DECAP",
            DebugEventType::DbgPortMap => "DBG_PORT_MAP",
            DebugEventType::DbgErrorRet => "DBG_ERROR_RET",
            DebugEventType::DbgToHost => "DBG_TO_HOST",
            DebugEventType::DbgToStack => "DBG_TO_STACK",
            DebugEventType::DbgPktHash => "DBG_PKT_HASH",
            DebugEventType::DbgLb6LookupFrontend => "DBG_LB6_LOOKUP_FRONTEND",
            DebugEventType::DbgLb6LookupFrontendFail => "DBG_LB6_LOOKUP_FRONTEND_FAIL",
            DebugEventType::DbgLb6LookupBackendSlot => "DBG_LB6_LOOKUP_BACKEND_SLOT",
            DebugEventType::DbgLb6LookupBackendSlotSuccess => {
                "DBG_LB6_LOOKUP_BACKEND_SLOT_SUCCESS"
            }
            DebugEventType::DbgLb6LookupBackendSlotV2Fail => {
                "DBG_LB6_LOOKUP_BACKEND_SLOT_V2_FAIL"
            }
            DebugEventType::DbgLb6LookupBackendFail => "DBG_LB6_LOOKUP_BACKEND_FAIL",
            DebugEventType::DbgLb6ReverseNatLookup => "DBG_LB6_REVERSE_NAT_LOOKUP",
            DebugEventType::DbgLb6ReverseNat => "DBG_LB6_REVERSE_NAT",
            DebugEventType::DbgLb4LookupFrontend => "DBG_LB4_LOOKUP_FRONTEND",
            DebugEventType::DbgLb4LookupFrontendFail => "DBG_LB4_LOOKUP_FRONTEND_FAIL",
            DebugEventType::DbgLb4LookupBackendSlot => "DBG_LB4_LOOKUP_BACKEND_SLOT",
            DebugEventType::DbgLb4LookupBackendSlotSuccess => {
                "DBG_LB4_LOOKUP_BACKEND_SLOT_SUCCESS"
            }
            DebugEventType::DbgLb4LookupBackendSlotV2Fail => {
                "DBG_LB4_LOOKUP_BACKEND_SLOT_V2_FAIL"
            }
            DebugEventType::DbgLb4LookupBackendFail => "DBG_LB4_LOOKUP_BACKEND_FAIL",
            DebugEventType::DbgLb4ReverseNatLookup => "DBG_LB4_REVERSE_NAT_LOOKUP",
            DebugEventType::DbgLb4ReverseNat => "DBG_LB4_REVERSE_NAT",
            DebugEventType::DbgLb4LoopbackSnat => "DBG_LB4_LOOPBACK_SNAT",
            DebugEventType::DbgLb4LoopbackSnatRev => "DBG_LB4_LOOPBACK_SNAT_REV",
            DebugEventType::DbgCtLookup4 => "DBG_CT_LOOKUP4",
            DebugEventType::DbgRrBackendSlotSel => "DBG_RR_BACKEND_SLOT_SEL",
            DebugEventType::DbgRevProxyLookup => "DBG_REV_PROXY_LOOKUP",
            DebugEventType::DbgRevProxyFound => "DBG_REV_PROXY_FOUND",
            DebugEventType::DbgRevProxyUpdate => "DBG_REV_PROXY_UPDATE",
            DebugEventType::DbgL4Policy => "DBG_L4_POLICY",
            DebugEventType::DbgNetdevInCluster => "DBG_NETDEV_IN_CLUSTER",
            DebugEventType::DbgNetdevEncap4 => "DBG_NETDEV_ENCAP4",
            DebugEventType::DbgCtLookup41 => "DBG_CT_LOOKUP4_1",
            DebugEventType::DbgCtLookup42 => "DBG_CT_LOOKUP4_2",
            DebugEventType::DbgCtCreated4 => "DBG_CT_CREATED4",
            DebugEventType::DbgCtLookup61 => "DBG_CT_LOOKUP6_1",
            DebugEventType::DbgCtLookup62 => "DBG_CT_LOOKUP6_2",
            DebugEventType::DbgCtCreated6 => "DBG_CT_CREATED6",
            DebugEventType::DbgSkipProxy => "DBG_SKIP_PROXY",
            DebugEventType::DbgL4Create => "DBG_L4_CREATE",
            DebugEventType::DbgIpIdMapFailed4 => "DBG_IP_ID_MAP_FAILED4",
            DebugEventType::DbgIpIdMapFailed6 => "DBG_IP_ID_MAP_FAILED6",
            DebugEventType::DbgIpIdMapSucceed4 => "DBG_IP_ID_MAP_SUCCEED4",
            DebugEventType::DbgIpIdMapSucceed6 => "DBG_IP_ID_MAP_SUCCEED6",
            DebugEventType::DbgLbStaleCt => "DBG_LB_STALE_CT",
            DebugEventType::DbgInheritIdentity => "DBG_INHERIT_IDENTITY",
            DebugEventType::DbgSkLookup4 => "DBG_SK_LOOKUP4",
            DebugEventType::DbgSkLookup6 => "DBG_SK_LOOKUP6",
            DebugEventType::DbgSkAssign => "DBG_SK_ASSIGN",
            DebugEventType::DbgL7Lb => "DBG_L7_LB",
            DebugEventType::DbgSkipPolicy => "DBG_SKIP_POLICY",
            DebugEventType::DbgLb6LoopbackSnat => "DBG_LB6_LOOPBACK_SNAT",
            DebugEventType::DbgLb6LoopbackSnatRev => "DBG_LB6_LOOPBACK_SNAT_REV",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DBG_EVENT_UNKNOWN" => Some(Self::DbgEventUnknown),
            "DBG_GENERIC" => Some(Self::DbgGeneric),
            "DBG_LOCAL_DELIVERY" => Some(Self::DbgLocalDelivery),
            "DBG_ENCAP" => Some(Self::DbgEncap),
            "DBG_LXC_FOUND" => Some(Self::DbgLxcFound),
            "DBG_POLICY_DENIED" => Some(Self::DbgPolicyDenied),
            "DBG_CT_LOOKUP" => Some(Self::DbgCtLookup),
            "DBG_CT_LOOKUP_REV" => Some(Self::DbgCtLookupRev),
            "DBG_CT_MATCH" => Some(Self::DbgCtMatch),
            "DBG_CT_CREATED" => Some(Self::DbgCtCreated),
            "DBG_CT_CREATED2" => Some(Self::DbgCtCreated2),
            "DBG_ICMP6_HANDLE" => Some(Self::DbgIcmp6Handle),
            "DBG_ICMP6_REQUEST" => Some(Self::DbgIcmp6Request),
            "DBG_ICMP6_NS" => Some(Self::DbgIcmp6Ns),
            "DBG_ICMP6_TIME_EXCEEDED" => Some(Self::DbgIcmp6TimeExceeded),
            "DBG_CT_VERDICT" => Some(Self::DbgCtVerdict),
            "DBG_DECAP" => Some(Self::DbgDecap),
            "DBG_PORT_MAP" => Some(Self::DbgPortMap),
            "DBG_ERROR_RET" => Some(Self::DbgErrorRet),
            "DBG_TO_HOST" => Some(Self::DbgToHost),
            "DBG_TO_STACK" => Some(Self::DbgToStack),
            "DBG_PKT_HASH" => Some(Self::DbgPktHash),
            "DBG_LB6_LOOKUP_FRONTEND" => Some(Self::DbgLb6LookupFrontend),
            "DBG_LB6_LOOKUP_FRONTEND_FAIL" => Some(Self::DbgLb6LookupFrontendFail),
            "DBG_LB6_LOOKUP_BACKEND_SLOT" => Some(Self::DbgLb6LookupBackendSlot),
            "DBG_LB6_LOOKUP_BACKEND_SLOT_SUCCESS" => {
                Some(Self::DbgLb6LookupBackendSlotSuccess)
            }
            "DBG_LB6_LOOKUP_BACKEND_SLOT_V2_FAIL" => {
                Some(Self::DbgLb6LookupBackendSlotV2Fail)
            }
            "DBG_LB6_LOOKUP_BACKEND_FAIL" => Some(Self::DbgLb6LookupBackendFail),
            "DBG_LB6_REVERSE_NAT_LOOKUP" => Some(Self::DbgLb6ReverseNatLookup),
            "DBG_LB6_REVERSE_NAT" => Some(Self::DbgLb6ReverseNat),
            "DBG_LB4_LOOKUP_FRONTEND" => Some(Self::DbgLb4LookupFrontend),
            "DBG_LB4_LOOKUP_FRONTEND_FAIL" => Some(Self::DbgLb4LookupFrontendFail),
            "DBG_LB4_LOOKUP_BACKEND_SLOT" => Some(Self::DbgLb4LookupBackendSlot),
            "DBG_LB4_LOOKUP_BACKEND_SLOT_SUCCESS" => {
                Some(Self::DbgLb4LookupBackendSlotSuccess)
            }
            "DBG_LB4_LOOKUP_BACKEND_SLOT_V2_FAIL" => {
                Some(Self::DbgLb4LookupBackendSlotV2Fail)
            }
            "DBG_LB4_LOOKUP_BACKEND_FAIL" => Some(Self::DbgLb4LookupBackendFail),
            "DBG_LB4_REVERSE_NAT_LOOKUP" => Some(Self::DbgLb4ReverseNatLookup),
            "DBG_LB4_REVERSE_NAT" => Some(Self::DbgLb4ReverseNat),
            "DBG_LB4_LOOPBACK_SNAT" => Some(Self::DbgLb4LoopbackSnat),
            "DBG_LB4_LOOPBACK_SNAT_REV" => Some(Self::DbgLb4LoopbackSnatRev),
            "DBG_CT_LOOKUP4" => Some(Self::DbgCtLookup4),
            "DBG_RR_BACKEND_SLOT_SEL" => Some(Self::DbgRrBackendSlotSel),
            "DBG_REV_PROXY_LOOKUP" => Some(Self::DbgRevProxyLookup),
            "DBG_REV_PROXY_FOUND" => Some(Self::DbgRevProxyFound),
            "DBG_REV_PROXY_UPDATE" => Some(Self::DbgRevProxyUpdate),
            "DBG_L4_POLICY" => Some(Self::DbgL4Policy),
            "DBG_NETDEV_IN_CLUSTER" => Some(Self::DbgNetdevInCluster),
            "DBG_NETDEV_ENCAP4" => Some(Self::DbgNetdevEncap4),
            "DBG_CT_LOOKUP4_1" => Some(Self::DbgCtLookup41),
            "DBG_CT_LOOKUP4_2" => Some(Self::DbgCtLookup42),
            "DBG_CT_CREATED4" => Some(Self::DbgCtCreated4),
            "DBG_CT_LOOKUP6_1" => Some(Self::DbgCtLookup61),
            "DBG_CT_LOOKUP6_2" => Some(Self::DbgCtLookup62),
            "DBG_CT_CREATED6" => Some(Self::DbgCtCreated6),
            "DBG_SKIP_PROXY" => Some(Self::DbgSkipProxy),
            "DBG_L4_CREATE" => Some(Self::DbgL4Create),
            "DBG_IP_ID_MAP_FAILED4" => Some(Self::DbgIpIdMapFailed4),
            "DBG_IP_ID_MAP_FAILED6" => Some(Self::DbgIpIdMapFailed6),
            "DBG_IP_ID_MAP_SUCCEED4" => Some(Self::DbgIpIdMapSucceed4),
            "DBG_IP_ID_MAP_SUCCEED6" => Some(Self::DbgIpIdMapSucceed6),
            "DBG_LB_STALE_CT" => Some(Self::DbgLbStaleCt),
            "DBG_INHERIT_IDENTITY" => Some(Self::DbgInheritIdentity),
            "DBG_SK_LOOKUP4" => Some(Self::DbgSkLookup4),
            "DBG_SK_LOOKUP6" => Some(Self::DbgSkLookup6),
            "DBG_SK_ASSIGN" => Some(Self::DbgSkAssign),
            "DBG_L7_LB" => Some(Self::DbgL7Lb),
            "DBG_SKIP_POLICY" => Some(Self::DbgSkipPolicy),
            "DBG_LB6_LOOPBACK_SNAT" => Some(Self::DbgLb6LoopbackSnat),
            "DBG_LB6_LOOPBACK_SNAT_REV" => Some(Self::DbgLb6LoopbackSnatRev),
            _ => None,
        }
    }
}
