// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStatusRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStatusResponse {
    /// number of currently captured flows
    /// In a multi-node context, this is the cumulative count of all captured
    /// flows.
    #[prost(uint64, tag = "1")]
    pub num_flows: u64,
    /// maximum capacity of the ring buffer
    /// In a multi-node context, this is the aggregation of all ring buffers
    /// capacities.
    #[prost(uint64, tag = "2")]
    pub max_flows: u64,
    /// total amount of flows observed since the observer was started
    /// In a multi-node context, this is the aggregation of all flows that have
    /// been seen.
    #[prost(uint64, tag = "3")]
    pub seen_flows: u64,
    /// uptime of this observer instance in nanoseconds
    /// In a multi-node context, this field corresponds to the uptime of the
    /// longest living instance.
    #[prost(uint64, tag = "4")]
    pub uptime_ns: u64,
    /// number of nodes for which a connection is established
    #[prost(message, optional, tag = "5")]
    pub num_connected_nodes: ::core::option::Option<u32>,
    /// number of nodes for which a connection cannot be established
    #[prost(message, optional, tag = "6")]
    pub num_unavailable_nodes: ::core::option::Option<u32>,
    /// list of nodes that are unavailable
    /// This list may not be exhaustive.
    #[prost(string, repeated, tag = "7")]
    pub unavailable_nodes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Version is the version of Cilium/Hubble.
    #[prost(string, tag = "8")]
    pub version: ::prost::alloc::string::String,
    /// Approximate rate of flows seen by Hubble per second over the last minute.
    /// In a multi-node context, this is the sum of all flows rates.
    #[prost(double, tag = "9")]
    pub flows_rate: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFlowsRequest {
    /// Number of flows that should be returned. Incompatible with `since/until`.
    /// Defaults to the most recent (last) `number` flows, unless `first` is
    /// true, then it will return the earliest `number` flows.
    #[prost(uint64, tag = "1")]
    pub number: u64,
    /// first specifies if we should look at the first `number` flows or the
    /// last `number` of flows. Incompatible with `follow`.
    #[prost(bool, tag = "9")]
    pub first: bool,
    /// follow sets when the server should continue to stream flows after
    /// printing the last N flows.
    #[prost(bool, tag = "3")]
    pub follow: bool,
    /// blacklist defines a list of filters which have to match for a flow to be
    /// excluded from the result.
    /// If multiple blacklist filters are specified, only one of them has to
    /// match for a flow to be excluded.
    #[prost(message, repeated, tag = "5")]
    pub blacklist: ::prost::alloc::vec::Vec<super::flow::FlowFilter>,
    /// whitelist defines a list of filters which have to match for a flow to be
    /// included in the result.
    /// If multiple whitelist filters are specified, only one of them has to
    /// match for a flow to be included.
    /// The whitelist and blacklist can both be specified. In such cases, the
    /// set of the returned flows is the set difference `whitelist - blacklist`.
    /// In other words, the result will contain all flows matched by the
    /// whitelist that are not also simultaneously matched by the blacklist.
    #[prost(message, repeated, tag = "6")]
    pub whitelist: ::prost::alloc::vec::Vec<super::flow::FlowFilter>,
    /// Since this time for returned flows. Incompatible with `number`.
    #[prost(message, optional, tag = "7")]
    pub since: ::core::option::Option<::prost_types::Timestamp>,
    /// Until this time for returned flows. Incompatible with `number`.
    #[prost(message, optional, tag = "8")]
    pub until: ::core::option::Option<::prost_types::Timestamp>,
    /// FieldMask allows clients to limit flow's fields that will be returned.
    /// For example, {paths: \["source.id", "destination.id"\]} will return flows
    /// with only these two fields set.
    #[prost(message, optional, tag = "10")]
    pub field_mask: ::core::option::Option<::prost_types::FieldMask>,
    #[prost(message, optional, tag = "999")]
    pub experimental: ::core::option::Option<get_flows_request::Experimental>,
    /// extensions can be used to add arbitrary additional metadata to GetFlowsRequest.
    /// This can be used to extend functionality for other Hubble compatible
    /// APIs, or experiment with new functionality without needing to change the public API.
    #[prost(message, optional, tag = "150000")]
    pub extensions: ::core::option::Option<::prost_types::Any>,
}
/// Nested message and enum types in `GetFlowsRequest`.
pub mod get_flows_request {
    /// Experimental contains fields that are not stable yet. Support for
    /// experimental features is always optional and subject to change.
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Experimental {}
}
/// GetFlowsResponse contains either a flow or a protocol message.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFlowsResponse {
    /// Name of the node where this event was observed.
    #[prost(string, tag = "1000")]
    pub node_name: ::prost::alloc::string::String,
    /// Timestamp at which this event was observed.
    #[prost(message, optional, tag = "1001")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(oneof = "get_flows_response::ResponseTypes", tags = "1, 2, 3")]
    pub response_types: ::core::option::Option<get_flows_response::ResponseTypes>,
}
/// Nested message and enum types in `GetFlowsResponse`.
pub mod get_flows_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ResponseTypes {
        #[prost(message, tag = "1")]
        Flow(super::super::flow::Flow),
        /// node_status informs clients about the state of the nodes
        /// participating in this particular GetFlows request.
        #[prost(message, tag = "2")]
        NodeStatus(super::super::relay::NodeStatusEvent),
        /// lost_events informs clients about events which got dropped due to
        /// a Hubble component being unavailable
        #[prost(message, tag = "3")]
        LostEvents(super::super::flow::LostEvent),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAgentEventsRequest {
    /// Number of flows that should be returned. Incompatible with `since/until`.
    /// Defaults to the most recent (last) `number` events, unless `first` is
    /// true, then it will return the earliest `number` events.
    #[prost(uint64, tag = "1")]
    pub number: u64,
    /// first specifies if we should look at the first `number` events or the
    /// last `number` of events. Incompatible with `follow`.
    #[prost(bool, tag = "9")]
    pub first: bool,
    /// follow sets when the server should continue to stream agent events after
    /// printing the last N agent events.
    #[prost(bool, tag = "2")]
    pub follow: bool,
    /// Since this time for returned agent events. Incompatible with `number`.
    #[prost(message, optional, tag = "7")]
    pub since: ::core::option::Option<::prost_types::Timestamp>,
    /// Until this time for returned agent events. Incompatible with `number`.
    #[prost(message, optional, tag = "8")]
    pub until: ::core::option::Option<::prost_types::Timestamp>,
}
/// GetAgentEventsResponse contains an event received from the Cilium agent.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAgentEventsResponse {
    #[prost(message, optional, tag = "1")]
    pub agent_event: ::core::option::Option<super::flow::AgentEvent>,
    /// Name of the node where this event was observed.
    #[prost(string, tag = "1000")]
    pub node_name: ::prost::alloc::string::String,
    /// Timestamp at which this event was observed.
    #[prost(message, optional, tag = "1001")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDebugEventsRequest {
    /// Number of events that should be returned. Incompatible with `since/until`.
    /// Defaults to the most recent (last) `number` events, unless `first` is
    /// true, then it will return the earliest `number` events.
    #[prost(uint64, tag = "1")]
    pub number: u64,
    /// first specifies if we should look at the first `number` events or the
    /// last `number` of events. Incompatible with `follow`.
    #[prost(bool, tag = "9")]
    pub first: bool,
    /// follow sets when the server should continue to stream debug events after
    /// printing the last N debug events.
    #[prost(bool, tag = "2")]
    pub follow: bool,
    /// Since this time for returned debug events. Incompatible with `number`.
    #[prost(message, optional, tag = "7")]
    pub since: ::core::option::Option<::prost_types::Timestamp>,
    /// Until this time for returned debug events. Incompatible with `number`.
    #[prost(message, optional, tag = "8")]
    pub until: ::core::option::Option<::prost_types::Timestamp>,
}
/// GetDebugEventsResponse contains a Cilium datapath debug events.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDebugEventsResponse {
    #[prost(message, optional, tag = "1")]
    pub debug_event: ::core::option::Option<super::flow::DebugEvent>,
    /// Name of the node where this event was observed.
    #[prost(string, tag = "1000")]
    pub node_name: ::prost::alloc::string::String,
    /// Timestamp at which this event was observed.
    #[prost(message, optional, tag = "1001")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNodesRequest {}
/// GetNodesResponse contains the list of nodes.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNodesResponse {
    /// Nodes is an exhaustive list of nodes.
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<Node>,
}
/// Node represents a cluster node.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Node {
    /// Name is the name of the node.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Version is the version of Cilium/Hubble as reported by the node.
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// Address is the network address of the API endpoint.
    #[prost(string, tag = "3")]
    pub address: ::prost::alloc::string::String,
    /// State represents the known state of the node.
    #[prost(enumeration = "super::relay::NodeState", tag = "4")]
    pub state: i32,
    /// TLS reports TLS related information.
    #[prost(message, optional, tag = "5")]
    pub tls: ::core::option::Option<Tls>,
    /// UptimeNS is the uptime of this instance in nanoseconds
    #[prost(uint64, tag = "6")]
    pub uptime_ns: u64,
    /// number of currently captured flows
    #[prost(uint64, tag = "7")]
    pub num_flows: u64,
    /// maximum capacity of the ring buffer
    #[prost(uint64, tag = "8")]
    pub max_flows: u64,
    /// total amount of flows observed since the observer was started
    #[prost(uint64, tag = "9")]
    pub seen_flows: u64,
}
/// TLS represents TLS information.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tls {
    /// Enabled reports whether TLS is enabled or not.
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// ServerName is the TLS server name that can be used as part of the TLS
    /// cert validation process.
    #[prost(string, tag = "2")]
    pub server_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNamespacesRequest {}
/// GetNamespacesResponse contains the list of namespaces.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNamespacesResponse {
    /// Namespaces is a list of namespaces with flows
    #[prost(message, repeated, tag = "1")]
    pub namespaces: ::prost::alloc::vec::Vec<Namespace>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Namespace {
    #[prost(string, tag = "1")]
    pub cluster: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub namespace: ::prost::alloc::string::String,
}
/// ExportEvent contains an event to be exported. Not to be used outside of the
/// exporter feature.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExportEvent {
    /// Name of the node where this event was observed.
    #[prost(string, tag = "1000")]
    pub node_name: ::prost::alloc::string::String,
    /// Timestamp at which this event was observed.
    #[prost(message, optional, tag = "1001")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(oneof = "export_event::ResponseTypes", tags = "1, 2, 3, 4, 5")]
    pub response_types: ::core::option::Option<export_event::ResponseTypes>,
}
/// Nested message and enum types in `ExportEvent`.
pub mod export_event {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ResponseTypes {
        #[prost(message, tag = "1")]
        Flow(super::super::flow::Flow),
        /// node_status informs clients about the state of the nodes
        /// participating in this particular GetFlows request.
        #[prost(message, tag = "2")]
        NodeStatus(super::super::relay::NodeStatusEvent),
        /// lost_events informs clients about events which got dropped due to
        /// a Hubble component being unavailable
        #[prost(message, tag = "3")]
        LostEvents(super::super::flow::LostEvent),
        /// agent_event informs clients about an event received from the Cilium
        /// agent.
        #[prost(message, tag = "4")]
        AgentEvent(super::super::flow::AgentEvent),
        /// debug_event contains Cilium datapath debug events
        #[prost(message, tag = "5")]
        DebugEvent(super::super::flow::DebugEvent),
    }
}
/// Generated client implementations.
pub mod observer_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Observer returns a stream of Flows depending on which filter the user want
    /// to observe.
    #[derive(Debug, Clone)]
    pub struct ObserverClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ObserverClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ObserverClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ObserverClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            ObserverClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// GetFlows returning structured data, meant to eventually obsolete GetLastNFlows.
        pub async fn get_flows(
            &mut self,
            request: impl tonic::IntoRequest<super::GetFlowsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::GetFlowsResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/observer.Observer/GetFlows",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("observer.Observer", "GetFlows"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// GetAgentEvents returns Cilium agent events.
        pub async fn get_agent_events(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAgentEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::GetAgentEventsResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/observer.Observer/GetAgentEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("observer.Observer", "GetAgentEvents"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// GetDebugEvents returns Cilium datapath debug events.
        pub async fn get_debug_events(
            &mut self,
            request: impl tonic::IntoRequest<super::GetDebugEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::GetDebugEventsResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/observer.Observer/GetDebugEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("observer.Observer", "GetDebugEvents"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// GetNodes returns information about nodes in a cluster.
        pub async fn get_nodes(
            &mut self,
            request: impl tonic::IntoRequest<super::GetNodesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetNodesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/observer.Observer/GetNodes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("observer.Observer", "GetNodes"));
            self.inner.unary(req, path, codec).await
        }
        /// GetNamespaces returns information about namespaces in a cluster.
        /// The namespaces returned are namespaces which have had network flows in
        /// the last hour. The namespaces are returned sorted by cluster name and
        /// namespace in ascending order.
        pub async fn get_namespaces(
            &mut self,
            request: impl tonic::IntoRequest<super::GetNamespacesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetNamespacesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/observer.Observer/GetNamespaces",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("observer.Observer", "GetNamespaces"));
            self.inner.unary(req, path, codec).await
        }
        /// ServerStatus returns some details about the running hubble server.
        pub async fn server_status(
            &mut self,
            request: impl tonic::IntoRequest<super::ServerStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ServerStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/observer.Observer/ServerStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("observer.Observer", "ServerStatus"));
            self.inner.unary(req, path, codec).await
        }
    }
}
