// This file is @generated by prost-build.
/// NodeStatusEvent is a message sent by hubble-relay to inform clients about
/// the state of a particular node.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeStatusEvent {
    /// state_change contains the new node state
    #[prost(enumeration = "NodeState", tag = "1")]
    pub state_change: i32,
    /// node_names is the list of nodes for which the above state changes applies
    #[prost(string, repeated, tag = "2")]
    pub node_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// message is an optional message attached to the state change (e.g. an
    /// error message). The message applies to all nodes in node_names.
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeState {
    /// UNKNOWN_NODE_STATE indicates that the state of this node is unknown.
    UnknownNodeState = 0,
    /// NODE_CONNECTED indicates that we have established a connection
    /// to this node. The client can expect to observe flows from this node.
    NodeConnected = 1,
    /// NODE_UNAVAILABLE indicates that the connection to this
    /// node is currently unavailable. The client can expect to not see any
    /// flows from this node until either the connection is re-established or
    /// the node is gone.
    NodeUnavailable = 2,
    /// NODE_GONE indicates that a node has been removed from the
    /// cluster. No reconnection attempts will be made.
    NodeGone = 3,
    /// NODE_ERROR indicates that a node has reported an error while processing
    /// the request. No reconnection attempts will be made.
    NodeError = 4,
}
impl NodeState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            NodeState::UnknownNodeState => "UNKNOWN_NODE_STATE",
            NodeState::NodeConnected => "NODE_CONNECTED",
            NodeState::NodeUnavailable => "NODE_UNAVAILABLE",
            NodeState::NodeGone => "NODE_GONE",
            NodeState::NodeError => "NODE_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_NODE_STATE" => Some(Self::UnknownNodeState),
            "NODE_CONNECTED" => Some(Self::NodeConnected),
            "NODE_UNAVAILABLE" => Some(Self::NodeUnavailable),
            "NODE_GONE" => Some(Self::NodeGone),
            "NODE_ERROR" => Some(Self::NodeError),
            _ => None,
        }
    }
}
